site_name: "CS 12 SI: Spring 2017"
pages:
    - [index.md, "Home"]
    - [dis01.md, "Discussion 1: CS 10 Review"]
   # - [lab01.md, "Lab 1: CS 10 Review"]
    - [dis01_2.md, "Lab 1: Selection Sort Case Study"]
   # - [lab02.md, "Lab Week 2: Streams"]
   # - [dis02_2.md, "Week 2 Dis 2: Merge Case Study"]
   # - [dis03_1.md, "Week 3 Dis 1: Classes"]
   # - [lab03.md, "Lab Week 3: Classes"]
   # - [dis03_2.md, "Week 3 Dis 2: Binary Search Case Study"]
   # - [dis04_1.md, "Week 4 Dis 1: Classes, Part 2"]
   # - [lab04.md, "Lab Week 4: Classes, Part 2"]
   # - [dis04_2.md, "Week 4 Dis 2: Rectangle"]
   # - [dis05_1.md, "Week 5 Dis 1: Midterm Reiew"]
   # - [lab05.md, "Lab Week 5: Midterm Review and Arrays"]
   # - [dis05_2.md, "Week 5 Dis 2: Cstrings"]
   # - [dis06_1.md, "Week 6 Dis 1: Pointers and Dynamic Memory"]
   # - [lab06.md, "Lab Week 6: Valgrind, Dynamic Memory, and Pointers"]
   # - [dis06_2.md, "Week 6 Dis 2: Choose Your Own Exercise"]
   # - [dis07_1.md, "Week 7 Dis 1: Linked List Basics"]
   # - [lab07.md, "Lab Week 7: Trains, Cars, and Dynamic Memory"]
   # - [dis07_2.md, "Week 7 Dis 2: Trains, Cars, and Dynamic Memory"]
   # - [dis08_1.md, "Week 8 Dis 1: Midterm Review and Recursion"]
   # - [lab08.md, "Lab Week 8: Recursion"]
   # - [dis08_2.md, "Week 8 Dis 2: strcpy and strcmp or Merge Sort"]
   # - [dis09_1.md, "Week 9 Dis 1: Inheritance"]
   # - [lab09.md, "Lab Week 9: Polymorphism"]
   # - [dis09_2.md, "Week 9 Dis 2: Lab9, part 2"]
   # - [dis10_1.md, "Week 10 Dis 1: Searching, Sorting, and Runtime"]
   # - [lab10.md, "Lab Week 10: Big-O, and Review"]
theme: readthedocs

