site_name: "CS 12 SI: Spring 2017"
pages:
    - [index.md, "Home"]
    - [lab01.md, "Week 1 Lab: CS 10 Review"]
    - [dis01_2.md, "Week 1 Dis 2: Selection Sort Case Study"]
    - [lab02.md, "Lab Week 2: Streams"]
    - [dis02_2.md, "Week 2 Dis 2: Merge Case Study"]
    - [dis03_1.md, "Week 3 Dis 1: Classes"]
    - [lab03.md, "Lab Week 3: Classes"]
    - [dis03_2.md, "Week 3 Dis 2: Binary Search Case Study"]
    - [dis04_1.md, "Week 4 Dis 1: Classes, Part 2"]
    - [lab04.md, "Lab Week 4: Classes, Part 2"]
    - [dis04_2.md, "Week 4 Dis 2: Rectangle"]
    #- [dis05_1.md, "Week 5 Dis 1: Midterm Reiew"]
theme: readthedocs

