site_name: "CS 12 SI: Spring 2017"
pages:
    - [index.md, "Home"]
    - [lab01.md, "Week 1 Lab: CS 10 Review"]
    - [dis01_2.md, "Week 1 Dis 2: Selection Sort Case Study"]
    - [lab02.md, "Lab Week 2: Streams"]
    - [dis02_2.md, "Week 2 Dis 2: Case Study"]
    #- [lab_week_04.md, "Lab Week 4"]
    #- [lab_week_05.md, "Lab Week 5"]
    #- [lab_week_06.md, "Lab Week 6"]
    #- [lab_week_07.md, "Lab Week 7"]
    #- [lab_week_08.md, "Lab Week 8"]
    #- [dis_week_08.md, "Discussion Week 8"]
    #- [lab_week_09.md, "Lab Week 9"]
    #- [lab_week_10.md, "Lab Week 10"]
    #- [notes.md, "Notes"]
theme: readthedocs

